#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Sep  3 19:58:07 2018

@author: piter
"""

#def sortowanie(a, b, c, d):
#    print("sortowanie")
#    if a <= b and a <= c and a <=d:
#        print(a)
 #   else:
  #      print(b) 
 #   
 #   for x in 
#sortowanie(102, 85, 100, 50)
 
# 50
# 85
# 100
# 102

list=[5, 4, 3, 2]
list2=[5, 4, 3, 2]
print(list2)
if list2[1] < list2[0]:
    temp0 = list2[0]
    list2[0] = list2[1]
    list2[1] = temp0
    print(list2)
    
if list2[2] < list2[1]:
    temp1 = list2[2]
    list2[2] = list2[1]
    list2[1] = temp1
    print(list2)

if list2[3] < list2[2]:
    temp1 = list2[3]
    list2[3] = list2[2]
    list2[2] = temp1
    print(list2)
    
if list2[1] < list2[0]:
    temp0 = list2[0]
    list2[0] = list2[1]
    list2[1] = temp0
    print(list2)
    
if list2[2] < list2[1]:
    temp1 = list2[2]
    list2[2] = list2[1]
    list2[1] = temp1
    print(list2)
    
if list2[3] < list2[2]:
    temp1 = list2[3]
    list2[3] = list2[2]
    list2[2] = temp1
    print(list2)

if list2[1] < list2[0]:
    temp0 = list2[0]
    list2[0] = list2[1]
    list2[1] = temp0
    print(list2)

print("posortowane:")
for x in range(len(list)-1,0,-1):
    for i in range(x):
        if list[i] > list[i+1]:
            temp = list[i]
            list[i] = list[i+1]
            list[i+1] = temp
print(list)
print(range(len(list)))
for x in range(len(list)):
    print(x)
            
    
